### ISSUE TITLE
some issues

### ISSUE THREAD

**Issue by zbeekman** [hornekyle/PlPlotLib#2]
Before I submit pull requests, to address some things, I first wanted to ask you about them, to check if what appear to me as issues/oversights were in fact intentional on your part:
1. In the FORD project file the media dir points to what appears to be an absolute path in your home directory rather than a project relative path. Was that intentional?
2. In the makefile, there appears to be an extraneous ‘d’ character in the `plplot-f95` package config package name. (`plplotd-f95` vs `plplot-f95`)

**Comment by hornekyle** [comment]
The pkg-config entries on Debian stable name the library as is found in the makefile. Which platform are you on? If we can make this more generic, I would welcome the changes.

As for the media path, it was temporarily set as absolute in an attempt at working around a bug in the version of FORD on PyPI. I welcome any solution.

**Comment by zbeekman** [comment]
> The pkg-config entries on Debian stable name the library as is found in the makefile. Which platform are you on? If we can make this more generic, I would welcome the changes.

That’s obnoxious… on Mac installing via homebrew sets the names to the expected values without the ‘d’. I guess this might be a bit more involved than anticipated.

> As for the media path, it was temporarily set as absolute in an attempt at working around a bug in the version of FORD on PyPI. I welcome any solution.

Ah I see. Let me play around with it. If I can come up with something slick I’ll submit a PR.

Thanks for getting back to me and for the nice wrapper!

**Comment by hornekyle** [comment]
I think that the d at the end of the name in pkg-config on Debian signifies that it is the double precision version of the library. Some other libraries follow similar naming conventions.

I have been considering moving the build system to cmake, since I find it more flexible. I was just using plain makefiles in the initial development phase.

If I switch to cmake I'll try to remove the dependence on pkg-config and just use cmake's find\* tools.

**Comment by zbeekman** [comment]
wow, you were reading my mind about CMake… at least on Mac OS X with Homebrew, plplot seems to provide target export packages under `lib/cmake/plplot/`which may be able to be used in place of pkg-config

**Comment by hornekyle** [comment]
On Linux to I prefer to use cmake on bigger projects. I'll make the changes on the main branch.

**Comment by hornekyle** [comment]
There is now a cmake build system as well, which has been tested on Debian. It relies on cmake's pkg-config support, but allows for multiple possible names of the plplot package.

I'll close this issue and create a new one for the documentation matters.
