### ISSUE TITLE
Sort out references in FORD

### ISSUE THREAD

**Issue by hornekyle** [hornekyle/PlPlotLib#3]
References to images and links to program units are not currently working.

**Comment by zbeekman** [comment]
just curious, are you running the latest release? Is this a currently open FORD bug?

**Comment by hornekyle** [comment]
I've reported the issue to FORD's author, and ib think that he has fixed it. I'm still running the version on PyPI.

-------- Original Message --------

**Comment by hornekyle** [comment]
Should be fixed in update.
